# config/settings.py
version: '3.8'

services:
  web:
    build: .
    command: python /home/joonyi/PycharmProjects/django-prof/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/joonyi/PycharmProjects/django-prof
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=is#^c!dd3sv50!75xzxr5z*q_je1z^ki+ez4orm(d3y!1t!j$$q"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
